email verification implementation
AssociazionePrometeo/gianomanager pull request #40
Opened 2017-05-11 21:33 UTC by giutrec

Added user email verification

2017-05-11 21:51 UTC, mattbit requested changes

2017-05-11 21:51 UTC, mattbit commented on app/Http/Controllers/Auth/RegisterController.php
> +            'email_token' => str_random(10),
Non ci costa niente uno `str_random(64)`

2017-05-11 21:51 UTC, mattbit commented on app/Http/Controllers/Auth/RegisterController.php
> +            'email_token' => str_random(10),
(10 è sicuramente troppo poco)

2017-05-11 21:55 UTC, mattbit requested changes

2017-05-11 21:55 UTC, mattbit commented on app/Http/Controllers/Auth/RegisterController.php
> +    DB::beginTransaction();
La transaction non è necessaria, l’utente lo salviamo comunque.

2017-05-11 21:55 UTC, mattbit commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->tinyInteger('verified')->default(0);
Da mettere in una migration separata. Usiamo anche il tipo `boolean`.

2017-05-11 21:55 UTC, mattbit commented on app/User.php
> +    public function verified()
L’azione è `verify()`.

2017-05-11 21:56 UTC, mattbit commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->tinyInteger('verified')->default(0);
Vedi se usare uno status oppure un nome più esplicito per la coppia `active` e `verified`.

2017-05-12 14:31 UTC, giutrec commented on app/User.php
> +    public function verified()
verify() è già un azione, in cui fa la verifica (nel registercontroller), verified() è l'azione che cambia lo stato del campo verified portandolo ad 1

2017-05-12 14:31 UTC, giutrec commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->tinyInteger('verified')->default(0);
pensavo di lasciarlo a coppia modificando verified in email_verified

2017-05-12 14:31 UTC, giutrec commented on app/Http/Controllers/Auth/RegisterController.php
> +            'email_token' => str_random(10),
ok

2017-05-12 14:31 UTC, giutrec commented on app/Http/Controllers/Auth/RegisterController.php
> +    DB::beginTransaction();
ok

2017-05-12 14:31 UTC, giutrec commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->tinyInteger('verified')->default(0);
perchè separare le migration?

2017-05-12 14:38 UTC, mattbit approved these changes

2017-05-12 14:38 UTC, mattbit commented on app/User.php
> +    public function verified()
Quel che intendo è che dato che il metodo apporta cambiamenti al modello va messo un verbo attivo: `$user->verify()`, come `$user->save()` o `$user->delete()` e non `$user->saved()` o `$user->deleted()`.
Da un metodo `verified` mi aspetto invece un valore e.g. `if ($user->verified()) { … }`.

2017-05-12 16:04 UTC, giutrec commented on app/User.php
> +    public function verified()
ok ho capito, l'ho modificato in verify, ed il check che verifica se è verificato (che si chiamava a sua volta verify, l'ho chiamato ifverify)

2017-05-12 16:08 UTC, merged